spring.application.name=IT23234048
server.port=8081
spring.data.mongodb.uri=mongodb+srv://campus_admin:system@cluster0.qt58zrc.mongodb.net/studentdb?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://campus_admin:system@cluster0.qt58zrc.mongodb.net/studentdb?retryWrites=true&w=majority
spring.data.mongodb.database=studentdb
spring.data.mongodb.auto-index-creation=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
ticket.upload.path=./uploads/tickets/